
#+TITLE: Колоды Anki
#+AUTHOR: Константин Моренко
#+EMAIL: web@konstantin-morenko.ru

* Назначение

Этот репозитарий содержит все мои колоды для [[https://apps.ankiweb.net/][Anki]].

* Система версий

Версии колоды состоят из двух цифр: минорного номера и патча.
Аналогично ~semver~, только короче.  Если колода претерпевает такие
изменения, которые требуют изменения мажорного номера (обычно это
структура карточек), то создается новая колода с новыми карточками.

Минорный номер (первый) означает расширение колоды новыми карточками,
патч (второй) означает исправление ошибок в существующих карточках.

* Структура

Структура записей:
- [Hotkey] Inkscape :: Горячие клавиши (Hotkey) для Inkscape

Колоды разделены на тематические группы.  Группами являются:
- Languages :: естественные языки
  - Esperanto :: Эсперанто
    - Lernu :: Lernu.net
- языки программирования
- Programs :: офисные пакеты/программы
  - Inkscape :: Векторный редактор
    - Hotkeys :: Горячие клавиши
  - MS Word :: Да, этот самый текстовый редактор
    - Hotkeys :: Горячие клавиши
      - dialog :: Открывает диалоговое окно
      - selection :: Оперирует с выделением
      - font :: Оперирует параметрами шрифта
      - format :: Оперирует форматированием
      - paragraph :: Оперирует с абзацем
      - style :: Оперирует стилями
      - other :: Другие операции
      - document :: Оперирует документами и окнами
      - clipboard :: Оперирует буфером обмена
      - mouse :: Выполняется мышью
      - cursor :: Двигает курсор
      - word :: Оперирует с текущим словом
      - editing :: Редактирует содержимое
    - Equations :: Быстрые операции в форматировании формул
- темы

Структура групп/колод повторяет структуру файлов в системе.

* Hotkey

В горячих клавишах порядок следования модификаторов:
#+begin_verse
[Win+][Ctrl+][Shift+][Alt+]<Key>
#+end_verse
При этом клавиша может обозначать как нижний символ, так и верхний.
Для верхнего символа всегда будет указан Shift в качестве
модификатора.  Комбинация указывается без пробелов (учитывайте при
поиске).  Если команда может вызываться несколькими комбинациями, они
отделяются тремя пробелами.  Если команда составная (цепь в Emacs), то
отдельные звенья отделяются пробелом.  Раскладка всегда предполагается
QWERTY.

* Маркировки

Маркировка общая для всех колод.

** Флаги

- красный ::
- оранжевый :: карточка нуждается в уточнении/переработке
- зеленый ::
- синий ::
- розовый ::
- бирюзовый ::
- фиолетовый ::

* Как заучивать горячие клавиши

Первоначальная подготовка:
- Переведите все карточки в "Отложенные" (в просмотре колод с помощью
  контекстного меню "Карточки/Исключить-включить" или ~Ctrl+J~).
- Просматривайте колоду и включайте те карточки, о назначении которых
  вы знаете (например, всем известна команда "Сохранить" и что она
  делает).  Если вы не знаете назначение той или иной команды,
  оставьте карточку "Исключенной".
- Заучивайте известные вам команды

Через некоторое время, когда вы освоите многие из известных вам
команд:
- Снова просмотрите колоду с фильтром "Исключенных" карточек
- Изучите функции, которые стоят за ними, почитайте в Интернете,
  попробуйте самостоятельно
- Включите эти карточки и продолжайте заучивать
- При необходимости, добавьте свои собственные карточки с нужными вам
  горячими клавишами

Повторяйте эту процедуру до тех пор, пока не освоите все горячие
клавиши или пока не освоите все /нужные вам/ горячие клавиши.
